//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MotionPanel64.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOTIONPANEL64_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_AIXS                        130
#define IDD_CONFIG                      131
#define IDD_VER                         132
#define IDD_IO                          133
#define IDC_CARD                        1000
#define IDC_TAB_MAIN                    1001
#define IDC_IN0                         1002
#define IDC_APP_VER                     1003
#define IDC_IN1                         1004
#define IDC_SPEED_X                     1005
#define IDC_IN2                         1006
#define IDC_CMDPOS_X                    1007
#define IDC_IN3                         1008
#define IDC_API_VER                     1009
#define IDC_ENCPOS_X                    1010
#define IDC_IN4                         1011
#define IDC_DRV_VER                     1012
#define IDC_PEL_X                       1013
#define IDC_IN5                         1014
#define IDC_LOGIC_VER                   1015
#define IDC_MEL_X                       1016
#define IDC_IN6                         1017
#define IDC_ORG_X                       1018
#define IDC_IN7                         1019
#define IDC_STATUS_X                    1020
#define IDC_IN8                         1021
#define IDC_SPEED_Y                     1022
#define IDC_IN9                         1023
#define IDC_CMDPOS_Y                    1024
#define IDC_IN10                        1025
#define IDC_ENCPOS_Y                    1026
#define IDC_IN11                        1027
#define IDC_PEL_Y                       1028
#define IDC_IN12                        1029
#define IDC_MEL_Y                       1030
#define IDC_IN13                        1031
#define IDC_ORG_Y                       1032
#define IDC_IN14                        1033
#define IDC_STATUS_Y                    1034
#define IDC_IN15                        1035
#define IDC_SPEED_Z                     1036
#define IDC_CMDPOS_Z                    1037
#define IDC_ENCPOS_Z                    1038
#define IDC_OUT0                        1039
#define IDC_PEL_Z                       1040
#define IDC_OUT1                        1041
#define IDC_MEL_Z                       1042
#define IDC_OUT2                        1043
#define IDC_ORG_Z                       1044
#define IDC_OUT3                        1045
#define IDC_STATUS_Z                    1046
#define IDC_OUT4                        1047
#define IDC_SPEED_U                     1048
#define IDC_OUT5                        1049
#define IDC_CMDPOS_U                    1050
#define IDC_OUT6                        1051
#define IDC_ENCPOS_U                    1052
#define IDC_OUT7                        1053
#define IDC_PEL_U                       1054
#define IDC_MEL_U                       1055
#define IDC_OUT8                        1056
#define IDC_ORG_U                       1057
#define IDC_OUT9                        1058
#define IDC_STATUS_U                    1059
#define IDC_OUT10                       1060
#define IDC_DEST_POS_X                  1061
#define IDC_OUT11                       1062
#define IDC_DEST_POS_Y                  1063
#define IDC_OUT12                       1064
#define IDC_DEST_POS_Z                  1065
#define IDC_OUT13                       1066
#define IDC_DEST_POS_U                  1067
#define IDC_OUT14                       1068
#define IDC_P_RUN                       1069
#define IDC_OUT15                       1070
#define IDC_V_RUNP                      1071
#define IDC_V_RUN_P                     1072
#define IDC_V_RUN_N                     1073
#define IDC_HOME_P                      1074
#define IDC_HOME_N                      1075
#define IDC_X                           1076
#define IDC_Y                           1077
#define IDC_Z                           1078
#define IDC_U                           1079
#define IDC_CMD_RUN                     1080
#define IDC_CMD_ESTOP                   1081
#define IDC_MODEL_PULSE                 1082
#define IDC_CMD_STOP                    1083
#define IDC_MODEL_CWCCW                 1084
#define IDC_CLEAR_POS                   1085
#define IDC_BACK_PULSE                  1086
#define IDC_BACK_AB                     1087
#define IDC_ORG                         1088
#define IDC_ORG_EZ                      1089
#define IDC_EZ_LOW                      1090
#define IDC_EZ_HIGH                     1091
#define IDC_T_TYPE                      1092
#define IDC_S_TYPE                      1093
#define IDC_LIMIT_LOW                   1094
#define IDC_VEL_START                   1095
#define IDC_LIMIT_HIGH                  1096
#define IDC_VEL_MAX                     1097
#define IDC_ACC                         1098
#define IDC_DEC                         1099
#define IDC_JERK                        1100
#define IDC_SET_X                       1101
#define IDC_SET_Y                       1102
#define IDC_SET_Z                       1103
#define IDC_SET_U                       1104
#define IDC_APPLY                       1105
#define IDC_INC_RUN                     1106
#define IDC_SPEED_LOW                   1107
#define IDC_SPEED_HIGH                  1108
#define IDC_SPEED_INCREASE              1109
#define IDC_DER_CHANGE_X                1110
#define IDC_DER_CHANGE_Y                1111
#define IDC_DER_CHANGE_Z                1112
#define IDC_DER_CHANGE_U                1113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
